backend:
  name: github
  repo: hikesilent/rybkiparty
  branch: main
  site_domain: rybki.party
  base_url: https://api.netlify.com
  auth_endpoint: https://api.netlify.com/auth
  auth_scope: public_repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

local_backend: true  # Opcjonalne - tylko do testów lokalnych
publish_mode: editorial_workflow  # Opcjonalne - wersje robocze

collections:
  - name: "posts"
    label: "Posty"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Tytuł", widget: "string" }
      - { name: "image", label: "Zdjęcie", widget: "image", required: false }
      - { name: "tags", label: "Tagi", widget: "list", required: false }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Treść", widget: "markdown" }