backend:
  name: git-gateway
  repo: hikesilent/rybkiparty
  branch: main
  site_domain: rybki.party

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posty"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:  # UWAGA: fields MUSI być tablicą
      - { name: "title", label: "Tytuł", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Treść", widget: "markdown" }
      - { name: "image", label: "Zdjęcie", widget: "image", required: false }
      - { name: "tags", label: "Tagi", widget: "list", required: false }